#' @importFrom data.table :=
#' @importFrom data.table %chin%
NULL


# Make sure data.table knows we know we're using it
.datatable.aware <- TRUE

# Prevent R CMD check from complaining about the standard data.table variables
utils::globalVariables(
  c(".",
    ".N",
    ".SD",
    "abs_rho",
    "CCLEName",
    "cId",
    "cotrt_value",
    "cotrt_value_zero",
    "DrugCombination",
    "ec50",
    "feat_val",
    "feature",
    "h",
    "is_bottom",
    "iso_level",
    "iso_source",
    "label",
    "legend_lbl_iso",
    "log10_ratio_conc",
    "log2_CI",
    "ModelID",
    "N",
    "NES",
    "p_value",
    "padj",
    "pos_x",
    "pos_y",
    "pval",
    "q_value",
    "ReadoutValue",
    "rId",
    "src",
    "stat_sig",
    "value",
    "WellColumn",
    "WellRow",
    "x",
    "x_0",
    "x_inf",
    "x_pos",
    "x_std",
    "y_pos",
    "conc",
    "dilution_drug",
    "Fixed_Conc_1",
    "Fixed_Conc_2",
    "Fixed_Label_1",
    "Fixed_Label_2",
    "Fixed_Name_1",
    "Fixed_Name_2",
    "name",
    "rank_1",
    "rank_2",
    "Row_Display_Name",
    "Treatment_Key"
  ),
  utils::packageName())
